version: '3.4'

services:
  cron:
    build:
      context: .
      dockerfile: ./Dockerfile.cron
    env_file: .env
    volumes:
      - ./cron/tasks/30min:/etc/periodic/30min
    depends_on:
      - postgres
  
  postgres:
    image: postgres:14.3
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
  
  plot:
    build:
      context: .
      dockerfile: ./Dockerfile.plot
    env_file: .env
    ports:
      - 5000:5000
    depends_on:
      - postgres
    volumes:
      - ./plot:/app/

volumes:
  pgdata: